/* ===========================================================
 * NetworkEvolutionPlugin : Cytoscape plugin for visualizing stages of
 * protein networks evolution.
 * ===========================================================
 *
 *
 * Project Info:  http://bioputer.mimuw.edu.pl/modevo/
 * Sources: http://code.google.com/p/misiek/
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 * [Java is a trademark or registered trademark of Sun Microsystems, Inc.
 * in the United States and other countries.]
 *
 * NetworkEvolutionPlugin  Copyright (C) 2008-2009
 * Authors:  Michal Wozniak (code) (m.wozniak@mimuw.edu.pl)
 *           Janusz Dutkowski (idea, data) (j.dutkowski@mimuw.edu.pl)
 *           Jerzy Tiuryn (supervisor) (tiuryn@mimuw.edu.pl)
 */

package ppine.ui.dataloading;

import javax.swing.border.TitledBorder;
import ppine.main.LoadedDataHandle;
import ppine.main.PluginDataHandle;

public class OneFileSpeciesInteractionsLoaderPanel extends javax.swing.JPanel {

    private String name;

    /** Creates new form SpeciesInteractionsLoaderPanel
     * @param name
     * @return 
     */
    public boolean checked() {
        return checkbox.isSelected();
    }

    public OneFileSpeciesInteractionsLoaderPanel(final String name) {
        initComponents();
        this.name = name;
        TitledBorder border = (TitledBorder) this.getBorder();
        border.setTitle(name);
        setActualLoadedUIState();
    }

    public Double tryGetTreshold() {
        if (checkbox.isSelected()) {
            try {
                Double treshold = Double.valueOf(tresholdField.getText());
                return treshold;
            } catch (NumberFormatException ex) {
                return null;
            }
        } else {
            return null;
        }
    }

    public String getSpeciesName() {
        return name;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkbox = new javax.swing.JCheckBox();
        tresholdField = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("species name"));

        checkbox.setSelected(true);
        checkbox.setName("checkbox"); // NOI18N

        tresholdField.setEnabled(false);
        tresholdField.setName("tresholdField"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(checkbox)
                .addGap(18, 18, 18)
                .addComponent(tresholdField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkbox)
                    .addComponent(tresholdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JTextField tresholdField;
    // End of variables declaration//GEN-END:variables

    public void setActualLoadedUIState() {
        LoadedDataHandle ldh = PluginDataHandle.getLoadedDataHandle();
        Double treshold = ldh.getSpeciesInteractionsTreshold(name);
        if (treshold == null) {
            checkbox.setSelected(true);
            tresholdField.setEnabled(true);
            tresholdField.setText("0.7");
        } else {
            checkbox.setSelected(true);
            tresholdField.setEnabled(true);
            if (treshold != null) {
                tresholdField.setText(String.valueOf(treshold));
            } else {
                tresholdField.setText("0.7");
            }
        }
    }
}
