package mcv.ui.logs;

import mcv.ui.PluginMenusHandle;

/**
 *
 * @author misiek
 */
public class LogsPanel extends javax.swing.JPanel {

    /** Creates new form LogsPanel */
    public LogsPanel() {
        initComponents();
        PluginMenusHandle.setMemo(loggerTextArea);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        loggerTextArea = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(280, 32767));
        setPreferredSize(new java.awt.Dimension(270, 124));

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        loggerTextArea.setEditable(false);
        loggerTextArea.setRows(5);
        loggerTextArea.setName("loggerTextArea"); // NOI18N
        jScrollPane2.setViewportView(loggerTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addGap(8, 8, 8)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea loggerTextArea;
    // End of variables declaration//GEN-END:variables
}
