/*
 * DataLoaderPanel.java
 *
 * Created on 2009-04-27, 15:57:08
 */
package mcv.ui.dataloading;

import javax.swing.JFrame;
import javax.swing.JTabbedPane;
import mcv.main.LoadedDataHandle;
import mcv.main.PluginDataHandle;
import mcv.ui.listeners.InteractionsLoadedListener;
import mcv.ui.listeners.ProteinsLoadedListener;
import mcv.ui.listeners.SpeciesLoadedListener;
import org.jdesktop.swingx.error.ErrorEvent;

/**
 *
 * @author misiek
 */
public class DataLoaderPanel extends javax.swing.JPanel {

    InteractionsLoaderPanel intLoader;
    SpeciesTreeLoaderPanel speciesTree;
    GenesTreesLoaderPanel genesTree;
    JFrame parentFrame;

    public void setParentFrameOnTop() {
        parentFrame.toFront();
    }

    public void refreshStats() {
        if (genesTree != null) {
            genesTree.refreshStats();
        }
    }

    public void showErrorOccuredLabel(ErrorEvent errorEvent) {
        errorLabel.setText("Some errors occured, see log for more details: " + errorEvent);

    }

    private void setActiveTab() {
        LoadedDataHandle ldh = PluginDataHandle.getLoadedDataHandle();
        if (ldh.isProteinsLoaded()) {
            this.getTabbedPane().setSelectedIndex(2);
        } else if (ldh.speciesTreeLoaded()) {
            this.getTabbedPane().setSelectedIndex(1);
        } else {
            this.getTabbedPane().setSelectedIndex(0);
        }
    }

    /*    private void setEnableSpeciesTab(boolean b) {
    this.getTabbedPane().setEnabledAt(0, b);
    }*/
    private void setEnableProteinsTab(boolean b) {
        this.getTabbedPane().setEnabledAt(1, b);
    }

    private void setEnableInteractionsTab(boolean b) {
        this.getTabbedPane().setEnabledAt(2, b);
    }

    /** Creates new form DataLoaderPanel
     * @param parentFrame
     */
    public DataLoaderPanel(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        InteractionsLoadedListener intlist = new InteractionsLoadedListener(this);
        intLoader = new InteractionsLoaderPanel(intlist);
        intLoader.setLoaderPanel(this);

        ProteinsLoadedListener list = new ProteinsLoadedListener(this, intLoader);
        SpeciesLoadedListener list2 = new SpeciesLoadedListener(this);

        speciesTree = new SpeciesTreeLoaderPanel(list2);
        speciesTree.setLoaderPanel(this);
        genesTree = new GenesTreesLoaderPanel(list);
        genesTree.setLoaderPanel(this);
        intLoader.setName("Interactions loading...");
        speciesTree.setName("Species tree loading...");
        genesTree.setName("Proteins data loading...");

        initComponents();
        this.getTabbedPane().addTab(speciesTree.getName(), speciesTree);
        this.getTabbedPane().addTab(genesTree.getName(), genesTree);
        this.getTabbedPane().addTab(intLoader.getName(), intLoader);

        enableTabs();
        setActiveTab();
    }

    public void enableTabs() {

        LoadedDataHandle ldh = PluginDataHandle.getLoadedDataHandle();
        setEnableProteinsTab(ldh.speciesTreeLoaded());
        setEnableInteractionsTab(ldh.isProteinsLoaded());
    }

    public JTabbedPane getTabbedPane() {
        return tabbedPane;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        logButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        errorLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        tabbedPane.setName("tabbedPane"); // NOI18N

        logButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mcv/resources/icons/stop2.png"))); // NOI18N
        logButton.setText("Show log");
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("mcv/ui/resources/Loading"); // NOI18N
        logButton.setToolTipText(bundle.getString("ShowLogButton.ToolTip")); // NOI18N
        logButton.setName("logButton"); // NOI18N
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        errorLabel.setBackground(new java.awt.Color(255, 0, 0));
        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setName("errorLabel"); // NOI18N
        jScrollPane3.setViewportView(errorLabel);

        closeButton.setText("Close ");
        closeButton.setToolTipText(bundle.getString("CloseButton.ToolTip")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(closeButton)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
        DefaultLoadingController.showMCVLogsPanel();
    }//GEN-LAST:event_logButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        parentFrame.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton logButton;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
