package panel;

public class AffinityPanel extends javax.swing.JPanel {

    private AffinityPanelController pc = null;

    /** Creates new form AffinityPanel */
    public AffinityPanel() {
        initComponents();
    }

    /** Creates new form AffinityPanel
     * @param pc
     */
    public AffinityPanel(final AffinityPanelController pc) {
        this.pc = pc;
        initComponents();
        pc.setCovitsField(convitsField);
        pc.setEdgeAttrField(edgeAttrCombo);
        pc.setNodeAttrField(nodeAttrNameField);
        pc.setIterationsField(iterationsSpinner);
        pc.setLambdaField(labmbdaField);
        pc.setPreferencesField(preferenceField);
        pc.setMatrixImplementation(radioMatrix);
        pc.setSmartImplementation(radioSibling);
        pc.initPanelFields();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioImplementationGroup = new javax.swing.ButtonGroup();
        startButton = new javax.swing.JButton();
        parametersPanel = new javax.swing.JPanel();
        edgeAttrNameLabel = new javax.swing.JLabel();
        nodeAttrNameLabel = new javax.swing.JLabel();
        nodeAttrNameField = new javax.swing.JTextField();
        iterationsSpinner = new javax.swing.JSpinner();
        iteretionsLabel = new javax.swing.JLabel();
        preferenceField = new javax.swing.JTextField();
        preferenceLabel = new javax.swing.JLabel();
        labmbdaField = new javax.swing.JTextField();
        lambdaLabel = new javax.swing.JLabel();
        convitsLabel = new javax.swing.JLabel();
        convitsField = new javax.swing.JTextField();
        edgeAttrCombo = new javax.swing.JComboBox();
        refreshButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        radioSibling = new javax.swing.JRadioButton();
        radioMatrix = new javax.swing.JRadioButton();

        startButton.setText("Start");
        startButton.setName("startButton"); // NOI18N
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        parametersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Set paremeters"));
        parametersPanel.setName("parametersPanel"); // NOI18N

        edgeAttrNameLabel.setText("Edge name attribute:");
        edgeAttrNameLabel.setName("edgeAttrNameLabel"); // NOI18N

        nodeAttrNameLabel.setText("Node name attribute:");
        nodeAttrNameLabel.setName("nodeAttrNameLabel"); // NOI18N

        nodeAttrNameField.setText("cluster_id");
        nodeAttrNameField.setName("nodeAttrNameField"); // NOI18N

        iterationsSpinner.setName("iterationsSpinner"); // NOI18N
        iterationsSpinner.setValue(10);

        iteretionsLabel.setText("Number of iterations:");
        iteretionsLabel.setName("iteretionsLabel"); // NOI18N

        preferenceField.setText("0.2");
        preferenceField.setToolTipText("Median is default and recommended");
        preferenceField.setName("preferenceField"); // NOI18N
        preferenceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferenceFieldActionPerformed(evt);
            }
        });

        preferenceLabel.setText("Preference:");
        preferenceLabel.setName("preferenceLabel"); // NOI18N

        labmbdaField.setText("0.5");
        labmbdaField.setName("labmbdaField"); // NOI18N
        labmbdaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labmbdaFieldActionPerformed(evt);
            }
        });

        lambdaLabel.setText("Lambda");
        lambdaLabel.setName("lambdaLabel"); // NOI18N

        convitsLabel.setText("Convits");
        convitsLabel.setName("convitsLabel"); // NOI18N

        convitsField.setText("3");
        convitsField.setName("convitsField"); // NOI18N

        edgeAttrCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        edgeAttrCombo.setName("edgeAttrCombo"); // NOI18N

        javax.swing.GroupLayout parametersPanelLayout = new javax.swing.GroupLayout(parametersPanel);
        parametersPanel.setLayout(parametersPanelLayout);
        parametersPanelLayout.setHorizontalGroup(
            parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parametersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(parametersPanelLayout.createSequentialGroup()
                            .addComponent(iteretionsLabel)
                            .addGap(19, 19, 19))
                        .addGroup(parametersPanelLayout.createSequentialGroup()
                            .addComponent(nodeAttrNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(parametersPanelLayout.createSequentialGroup()
                            .addComponent(edgeAttrNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(parametersPanelLayout.createSequentialGroup()
                            .addComponent(convitsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(parametersPanelLayout.createSequentialGroup()
                            .addComponent(preferenceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(parametersPanelLayout.createSequentialGroup()
                        .addComponent(lambdaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iterationsSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parametersPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nodeAttrNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parametersPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edgeAttrCombo, 0, 111, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parametersPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(convitsField, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                    .addComponent(preferenceField, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(labmbdaField, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addContainerGap())
        );
        parametersPanelLayout.setVerticalGroup(
            parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parametersPanelLayout.createSequentialGroup()
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nodeAttrNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nodeAttrNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edgeAttrNameLabel)
                    .addComponent(edgeAttrCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iterationsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iteretionsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convitsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convitsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preferenceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(preferenceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labmbdaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lambdaLabel))
                .addContainerGap(5, Short.MAX_VALUE))
        );

        refreshButton.setText("Refresh");
        refreshButton.setName("refreshButton"); // NOI18N
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose implementation"));
        jPanel2.setName("jPanel2"); // NOI18N

        radioImplementationGroup.add(radioSibling);
        radioSibling.setSelected(true);
        radioSibling.setText("Sibling lists");
        radioSibling.setToolTipText("faster");
        radioSibling.setName("radioSibling"); // NOI18N

        radioImplementationGroup.add(radioMatrix);
        radioMatrix.setText("Matrix");
        radioMatrix.setName("radioMatrix"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(radioMatrix)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(radioSibling)
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioSibling)
                    .addComponent(radioMatrix))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(parametersPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(parametersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refreshButton)
                    .addComponent(startButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed

        pc.doCluster();
}//GEN-LAST:event_startButtonActionPerformed

    private void preferenceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferenceFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_preferenceFieldActionPerformed

    private void labmbdaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labmbdaFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_labmbdaFieldActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        pc.refresh();
}//GEN-LAST:event_refreshButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField convitsField;
    private javax.swing.JLabel convitsLabel;
    private javax.swing.JComboBox edgeAttrCombo;
    private javax.swing.JLabel edgeAttrNameLabel;
    private javax.swing.JSpinner iterationsSpinner;
    private javax.swing.JLabel iteretionsLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField labmbdaField;
    private javax.swing.JLabel lambdaLabel;
    private javax.swing.JTextField nodeAttrNameField;
    private javax.swing.JLabel nodeAttrNameLabel;
    private javax.swing.JPanel parametersPanel;
    private javax.swing.JTextField preferenceField;
    private javax.swing.JLabel preferenceLabel;
    private javax.swing.ButtonGroup radioImplementationGroup;
    private javax.swing.JRadioButton radioMatrix;
    private javax.swing.JRadioButton radioSibling;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
