/*
 * GenesTreesLoaderPanel.java
 *
 * Created on 2009-04-27, 22:45:13
 */
package ui;

import java.awt.event.ActionEvent;
import java.io.File;
import javax.swing.JFileChooser;
import logicmodel.controllers.DataHandle;
import main.PluginDataHandle;
import ui.listeners.ProteinsLoadedListener;

/**
 *
 * @author misiek
 */
public class GenesTreesLoaderPanel extends javax.swing.JPanel {

    String filepath;
    ProteinsLoadedListener list;

    /** Creates new form GenesTreesLoaderPanel
     * @param list
     */
    public GenesTreesLoaderPanel(ProteinsLoadedListener list) {
        this.list = list;
        initComponents();
        initState();
    }

    public void initState() {
        DataHandle dh = PluginDataHandle.getDataHandle();
        if (dh.isProteinsLoaded()) {
            setLoadedState();
        } else {
            setUnloadedState();
        }
    }

    private void setFilenameLabel() {
        String filename = PluginDataHandle.getLoadingDataHandle().getGenesFilename();
        if (filename != null) {
            filenameLabel.setText(filename);
            filepath = filename;
        } else {
            loadButton.setEnabled(false);
        }
    }

    public void setLoadedState() {
        loadButton.setEnabled(false);
        chooseButton.setEnabled(false);
        setFilenameLabel();
    }

    public void setUnloadedState() {
        loadButton.setEnabled(true);
        chooseButton.setEnabled(true);
        setFilenameLabel();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filenameLabel = new javax.swing.JLabel();
        chooseButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();

        filenameLabel.setText("filename");
        filenameLabel.setName("filenameLabel"); // NOI18N

        chooseButton.setText("Choose file");
        chooseButton.setName("chooseButton"); // NOI18N
        chooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Load");
        loadButton.setName("loadButton"); // NOI18N
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chooseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loadButton, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                    .addComponent(filenameLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseButton)
                    .addComponent(loadButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filenameLabel)
                .addContainerGap(175, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(fc);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            filepath = file.getAbsolutePath();
            PluginDataHandle.getLoadingDataHandle().setGenesFilename(filepath);
            filenameLabel.setText(filepath);
            loadButton.setEnabled(true);
        }
    }//GEN-LAST:event_chooseButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        if (filepath != null) {
            UIController.getInstance().loadGenesTreeData(filepath);
            setLoadedState();
            list.actionPerformed(new ActionEvent(this, 2, "Proteins tree loaded"));
        }
    }//GEN-LAST:event_loadButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseButton;
    private javax.swing.JLabel filenameLabel;
    private javax.swing.JButton loadButton;
    // End of variables declaration//GEN-END:variables
}
